version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: heisenberg
    main: .
    binary: heisenberg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kamilpajak
    name: heisenberg
  prerelease: auto
  draft: false
  name_template: "v{{.Version}}"

brews:
  - name: heisenberg
    repository:
      owner: kamilpajak
      name: homebrew-tap
    homepage: https://github.com/kamilpajak/heisenberg
    description: AI-powered test failure analysis for GitHub repositories
    license: Apache-2.0
    install: |
      bin.install "heisenberg"
    test: |
      system "#{bin}/heisenberg", "--help"
    skip_upload: auto
